
Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.2.2"
  config.vm.synced_folder ".", "/vagrant"
  config.vm.provision "shell", path: "provision.sh" 
end
