
Vagrant.configure("2") do |config|
  
  config.vm.box = "centos/7"
  config.vm.hostname = "control-node"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network "private_network", ip: "192.168.1.2"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.provision "shell", path: "provision.sh"

end
